// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import "@vue/runtime-core";

declare module "@vue/runtime-core" {
  export interface GlobalComponents {
    Background: typeof import("./src/components/Blog/Background.vue")["default"];
    Banner: typeof import("./src/components/Blog/Banner.vue")["default"];
    Marzipano: typeof import("./src/components/marzipano.vue")["default"];
    MenuButton: typeof import("./src/components/Blog/NavBar/MenuButton.vue")["default"];
    NavBar: typeof import("./src/components/Blog/NavBar/NavBar.vue")["default"];
    NavTitle: typeof import("./src/components/Blog/NavBar/NavTitle.vue")["default"];
    RouterLink: typeof import("vue-router")["RouterLink"];
    RouterView: typeof import("vue-router")["RouterView"];
    Skeleton: typeof import("./src/components/Skeleton.vue")["default"];
    SvgBase: typeof import("./src/components/SvgBase.vue")["default"];
  }
}

export {};
