// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import "@vue/runtime-core";

declare module "@vue/runtime-core" {
  export interface GlobalComponents {
    NavBar: typeof import("./src/components/NavBar/NavBar.vue")["default"];
    NavTitle: typeof import("./src/components/NavBar/NavTitle.vue")["default"];
    RouterLink: typeof import("vue-router")["RouterLink"];
    RouterView: typeof import("vue-router")["RouterView"];
    SvgBase: typeof import("./src/components/SvgBase.vue")["default"];
  }
}

export {};
